### ISSUE TITLE
Skill not working with remote MQTT Server

### ISSUE THREAD

**Issue by happenpappen** [xinQuon/snipsSmallTalk_GER#1]
This skill is only working, if it is installed on the same server as the MQTT service. I've created a small patch (see attachement) which works on my installation... i think there have been some additions to the python API which offers a new way to connect - for example see here: https://github.com/Alpha200/snips-openhab/blob/master/action-openHAB.py

[smalltalk_ger.txt](https://github.com/xinQuon/snipsSmallTalk_GER/files/3470845/smalltalk_ger.txt)

**Comment by happenpappen** [comment]
Sorry, there are two things missing in my patch: You have to add "import toml" at the beginning of the action file and this module has to be added to requirements.txt:

toml>=0.10.0

**Comment by xinQuon** [comment]
Moin,
erstmal danke für den Patch! 
Bin neu in github und mache son bisschen learning by doing. Würde den patch gerne anwenden. Kannst du mir sagen wie ich das mit der von dir gelieferten smalltalk_ger.txt mache? Hab eben versucht in der bash "git am smalltalk_ger.txt" anzuwenden, läuft aber auf nen Fehler "Patch format detection failed."

Grüße aus Bremen

**Comment by xinQuon** [comment]
den import und requirements habe ich manuell angepasst

**Comment by happenpappen** [comment]
Ich bin auch nicht der Entwicklergott, hätte aber spontan gesagt, dass man den Patch mit "git apply <patch datei> anwenden können müsste...

Grüße aus dem Pott ;-)

**Comment by xinQuon** [comment]
ok - habs mit " git apply --ignore-space-change --ignore-whitespace smalltalk_ger.txt" gelöst. Ist nun drin. Bitte teste mal...

**Comment by xinQuon** [comment]
Der Patch hatte noch nen Fehler durch die nicht vordeklarierte Mqqt options. Ist korrigiert
